### ISSUE TITLE
 failed start app

### ISSUE THREAD

**Issue by EugeneBogush** [ttsou/openphy#1]
sudo ./ltedecode -c 1 -f 2661300000 -g 30
Config:
    Device args.............. ""
    Downlink frequency....... 2.661300 GHz
    Receive gain............. 30.0 dB
    Receive antennas......... 1
    Frequency reference...... Internal
    PDSCH decoding threads... 1
    LTE resource blocks...... 0
    LTE RNTI................. 0xffff (SI-RNTI)

[INFO] [UHDlinux; GNU C++ version 5.4.0 20160609; Boost_105800; UHD_3.11.0.git-208-g1da86f9c] 
[INFO] [B200] Loading firmware image: /usr/local/share/uhd/images/usrp_b200_fw.hex...
[INFO] [B200] 
13:38:44:891 DEV   : Opening device type=b200,name=MyB210,serial=309AF54,product=B210
[INFO] [B200] Detected Device: B210
[INFO] [B200] Loading FPGA image: /usr/local/share/uhd/images/usrp_b210_fpga.bin...

[INFO] [B200] Operating over USB 3.
[INFO] [B200] Detecting internal GPSDO.... 
[INFO] [GPS] No GPSDO found
[INFO] [B200] Initialize CODEC control...
[INFO] [B200] Initialize Radio control...
[INFO] [B200] Performing register loopback test... 
[INFO] [B200] pass
[INFO] [B200] Performing register loopback test... 
[INFO] [B200] pass
[INFO] [AD936X] Performing CODEC loopback test... 
[INFO] [AD936X] CODEC loopback test passed
[INFO] [AD936X] Performing CODEC loopback test... 
[INFO] [AD936X] CODEC loopback test passed
[INFO] [B200] Setting master clock rate selection to 'automatic'.
[INFO] [B200] Asking for clock rate 16.000000 MHz... 
[INFO] [B200] Actually got clock rate 16.000000 MHz.
[INFO] [CORES] Performing timer loopback test... 
[INFO] [CORES] Timer loopback test passed
[INFO] [CORES] Performing timer loopback test... 
[INFO] [CORES] Timer loopback test passed
13:39:03:424 DEV   :  - Invalid sample rate selection 0
[INFO] [B200] Asking for clock rate 32.000000 MHz... 
[INFO] [B200] Actually got clock rate 32.000000 MHz.
[INFO] [CORES] Performing timer loopback test... 
[INFO] [CORES] Timer loopback test passed
[INFO] [CORES] Performing timer loopback test... 
[INFO] [CORES] Timer loopback test passed
13:39:03:826 DEV   : Setting samples per packet to 2044
13:39:03:927 DEV   : Initial timestamp 4294967256
13:39:03:927 DEV   : Initial timestamp 4294967256DEV   : Invalid resource block 0
terminate called after throwing an instance of 'std::length_error'
  what():  vector::_M_default_append
Aborted (core dumped)

ubuntu 16.04

**Comment by vithyatith** [comment]
I'm having the same issue.

 sudo ltedecode -c 2 -f 2661300000 -g 30
Config:
    Device args.............. ""
    Downlink frequency....... 2.661300 GHz
    Receive gain............. 30.0 dB
    Receive antennas......... 2
    Frequency reference...... Internal
    PDSCH decoding threads... 1
    LTE resource blocks...... 0
    LTE RNTI................. 0xffff (SI-RNTI)

[INFO] [UHD] linux; GNU C++ version 5.4.0 20160609; Boost_105800; UHD_3.11.0.1-1-g1829d0fe
15:36:55:051 DEV   : Opening device type=b200,name=MyB210,serial=30EAE37,product=B210
[INFO] [B200] Detected Device: B210
[INFO] [B200] Operating over USB 3.
[INFO] [B200] Initialize CODEC control...
[INFO] [B200] Initialize Radio control...
[INFO] [B200] Performing register loopback test... 
[INFO] [B200] Register loopback test passed
[INFO] [B200] Performing register loopback test... 
[INFO] [B200] Register loopback test passed
[INFO] [AD936X] Performing CODEC loopback test... 
[INFO] [AD936X] CODEC loopback test passed
[INFO] [AD936X] Performing CODEC loopback test... 
[INFO] [AD936X] CODEC loopback test passed
[INFO] [B200] Setting master clock rate selection to 'automatic'.
[INFO] [B200] Asking for clock rate 16.000000 MHz... 
[INFO] [B200] Actually got clock rate 16.000000 MHz.
[INFO] [MULTI_USRP]     1) catch time transition at pps edge
[INFO] [MULTI_USRP]     2) set times next pps (synchronously)
15:36:58:389 DEV   :  - Invalid sample rate selection 0
15:36:58:412 DEV   : Setting samples per packet to 2044
15:36:58:513 DEV   : Initial timestamp 4294967256
15:36:58:513 DEV   : Initial timestamp 4294967256DEV   : Invalid resource block 0
terminate called after throwing an instance of 'std::length_error'
  what():  vector::_M_default_append
Aborted (core dumped)

ubuntu 16.04

**Comment by vithyatith** [comment]
I got it working by putting the resource block.

sudo ltedecode -c 2 -f 1955e6 -g 80 --rb 100 --threads 10
