### ISSUE TITLE
fail when dl bandwidth10Mhz

### ISSUE THREAD

**Issue by EugeneBogush** [ttsou/openphy#2]
./ltedecode -f 2630000000 -b 50 -c 1 -j 4
Config:
    Device args.............. ""
    Downlink frequency....... 2.630000 GHz
    Receive gain............. 50.0 dB
    Receive antennas......... 1
    Frequency reference...... Internal
    PDSCH decoding threads... 4
    LTE resource blocks...... 50
    LTE RNTI................. 0xffff (SI-RNTI)

[INFO] [UHDlinux; GNU C++ version 5.4.0 20160609; Boost_105800; UHD_3.11.0.git-208-g1da86f9c] 
14:53:50:676 DEV   : Opening device type=b200,name=B200mini,serial=30B0CDC,product=B200mini
[INFO] [B200] Detected Device: B200mini
[INFO] [B200] Operating over USB 3.
[INFO] [B200] Initialize CODEC control...
[INFO] [B200] Initialize Radio control...
[INFO] [B200] Performing register loopback test... 
[INFO] [B200] pass
[INFO] [AD936X] Performing CODEC loopback test... 
[INFO] [AD936X] CODEC loopback test passed
[INFO] [B200] Setting master clock rate selection to 'automatic'.
[INFO] [B200] Asking for clock rate 16.000000 MHz... 
[INFO] [B200] Actually got clock rate 16.000000 MHz.
[INFO] [CORES] Performing timer loopback test... 
[INFO] [CORES] Timer loopback test passed
14:53:52:262 DEV   : Setting rate to 11.52 MHz
[INFO] [MULTI_USRP] Setting master clock rate selection to 'manual'.
[INFO] [B200] Asking for clock rate 11.520000 MHz... 
[INFO] [B200] Actually got clock rate 11.520000 MHz.
[INFO] [CORES] Performing timer loopback test... 
[INFO] [CORES] Timer loopback test passed
14:53:52:764 DEV   : Setting samples per packet to 2044
14:53:52:864 DEV   : Initial timestamp 24515624
14:53:52:866 DEV   : Setting RF frequency to 2630 MHz
14:53:53:140 DEV   : Setting gain to 50 dB
14:53:53:190 FRAME : SFN 0025, Ns 00
14:53:53:190 PSS   : PSS detected, Magnitude 1226.000000, Timing offset 4996
14:53:53:190 STATE : State change from PSS-Sync0 to PSS-Sync1
14:53:53:190 DEV   : Received short packet
14:53:53:190 DEV   : Receive timed out
O14:53:53:191 FRAME : SFN 0026, Ns 00
14:53:53:191 PSS   : Frequency domain detection failed
14:53:53:191 PSS   : Time domain detection failed
14:53:53:191 STATE : State change from PSS-Sync1 to PSS-Sync0
14:53:53:197 FRAME : SFN 0029, Ns 00
14:53:53:197 PSS   : PSS detected, Magnitude 1700.000000, Timing offset 477
14:53:53:197 STATE : State change from PSS-Sync0 to PSS-Sync1
14:53:53:197 DEV   : Received short packet
14:53:53:197 DEV   : Receive timed out
O14:53:53:204 FRAME : SFN 0030, Ns 00
14:53:53:204 PSS   : PSS detected, Magnitude 29.167334, Timing offset 474
14:53:53:204 STATE : State change from PSS-Sync1 to SSS-Sync
14:53:54:204 SSS   : Cell ID 2, Slot 5, Offset 956.476013 Hz
14:53:54:205 DEV   : Adjusting DDC 956.476 Hz, DDC offset -956.476 Hz
14:53:54:205 STATE : Setting cellular ID 2
14:53:54:205 FRAME : SFN 0130, Ns 05
14:53:54:205 STATE : State change from SSS-Sync to PBCH-Sync
14:53:54:209 PSS   : PSS detected, Magnitude 30.944626, Timing offset 474
14:53:54:209 FRAME : SFN 0131, Ns 00
14:53:54:209 STATE : State change from PBCH-Sync to PBCH-Decode
14:53:54:210 PBCH  : MIB decoding failed
14:53:54:210 STATE : State change from PBCH-Decode to PBCH-Sync
14:53:54:220 PSS   : PSS detected, Magnitude 30.643265, Timing offset 474
14:53:54:220 FRAME : SFN 0132, Ns 00
14:53:54:220 STATE : State change from PBCH-Sync to PBCH-Decode
14:53:54:220 PBCH  : MIB decoding failed
14:53:54:220 STATE : State change from PBCH-Decode to PBCH-Sync
14:53:54:229 PSS   : PSS detected, Magnitude 28.293175, Timing offset 474
14:53:54:229 FRAME : SFN 0133, Ns 00
14:53:54:229 STATE : State change from PBCH-Sync to PBCH-Decode
14:53:54:230 PBCH  : Antennas 1, RBs = 50, FN = 824, PHICH duration = Normal, Ng = Sixth
14:53:54:230 FRAME : SFN 0824, Ns 00
14:53:54:230 STATE : State change from PBCH-Decode to PDSCH-Sync
14:53:54:338 PDCCH : DCI Length 27, CRC 65535, Agg. Level 4, Block 0
14:53:54:338 PDCCH : DCI Format 1A:
                     Format 0/1A differentiation              1
                     Local/distributed VRB assignment         0
                     Resource block assignment                150
                     Modulation and coding                    6
                     HARQ process number                      0
                     New data indicator                       0
                     Redundancy version                       0
                     TPC command for PUCCH                    0
14:53:54:338 PDSCH : RIV 150, start 0, N_step -1, L_crbs 4
No room left in precoding output buffer: 505-504
No room left in precoding output buffer: 507-504
No room left in precoding output buffer: 509-504
No room left in precoding output buffer: 511-504
No room left in precoding output buffer: 513-504
No room left in precoding output buffer: 515-504
No room left in precoding output buffer: 517-504
No room left in precoding output buffer: 519-504

**Comment by ttsou** [comment]
Thanks. Reproduced and fixed.
